name: fave_reads
description: A personal reading list application.
version: 0.5.0
author: Jermaine Oppong

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: ^2.5.0+1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
